server:
  port: 8080 # 서버 접속 포트 번호 (http://localhost:8080)

spring:
  application:
    name: shop # 프로젝트 애플리케이션 이름

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver # MariaDB와 연결하기 위한 드라이버
    url: jdbc:mariadb://localhost:3308/shop?serverTimezone=Asia/Seoul # DB 주소 및 타임존 설정
    username: root # DB 접속 아이디
    password: 1234 # DB 접속 비밀번호

  jpa:
    hibernate:
      ddl-auto: update # 엔티티 변경 시 DB 테이블을 자동으로 업데이트 (실무에선 주의!)
    show-sql: true # 실행되는 SQL문을 콘솔창에 출력
    properties:
      hibernate:
        format_sql: true # 콘솔에 출력되는 SQL문을 가독성 있게 정렬
    database-platform: org.hibernate.dialect.MariaDBDialect # MariaDB 전용 문법 사용 설정

  servlet:
    multipart:
      max-file-size: 20MB # 파일 하나당 최대 업로드 가능 크기
      max-request-size: 100MB # 한 번의 요청(여러 파일 포함)에 담을 수 있는 총 최대 크기



# --- 사용자 정의 설정 (ItemImgService 등에서 @Value로 참조) ---

# 실제 상품 이미지가 물리적으로 저장되는 서버 내부의 경로 (SSD/HDD 저장 위치)
itemImgLocation: c:/shop/item

# 웹 브라우저에서 이미지 주소로 접근할 때 사용하는 리소스 경로 (조회용)
# 예: file:///c:/shop 경로를 통해 브라우저가 파일을 읽어올 수 있도록 설정함
uploadPath: file:///c:/shop